import { createClient } from '@/lib/supabase/server'
import { NextResponse } from 'next/server'
import { sendWelcomeEmail } from '@/lib/email'
import { planClientLimit } from '@/lib/plans'
import { isExemptFromPaywall } from '@/lib/paywall'

export async function POST(req: Request) {
  const { email, coachId } = await req.json()

  if (!email?.trim() || !coachId) {
    return NextResponse.json({ error: 'Mangler e-postadresse' }, { status: 400 })
  }

  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  if (!user || user.id !== coachId) {
    return NextResponse.json({ error: 'Ikke autorisert' }, { status: 401 })
  }

  // ── Client limit (standalone coaches only) ────────────────────────────────
  // The org admin account and any coach who belongs to an organization are
  // exempt — organizations manage their own seat/client arrangements outside
  // this per-coach limit. Only a coach with no org membership is capped by
  // their subscription_plan.
  if (!(await isExemptFromPaywall(supabase, coachId))) {
    const { data: limitProfile } = await supabase
      .from('profiles')
      .select('subscription_plan')
      .eq('id', coachId)
      .single()

    const limit = planClientLimit(limitProfile?.subscription_plan)

    if (limit !== null) {
      const { count: clientCount } = await supabase
        .from('coach_clients')
        .select('id', { count: 'exact', head: true })
        .eq('coach_id', coachId)

      if ((clientCount ?? 0) >= limit) {
        const error = limit === 0
          ? 'Du må ha et aktivt abonnement for å legge til klienter. Oppgrader for å komme i gang.'
          : `Du har nådd grensen på ${limit} klienter for din plan. Oppgrader for å legge til flere.`
        return NextResponse.json({ error, limitReached: true }, { status: 403 })
      }
    }
  }

  const clientId = crypto.randomUUID()

  // No full_name here — the client sets their own real name during
  // onboarding (see /api/onboarding/[token]/set-password), so it's left
  // null rather than filled with a coach-typed placeholder.
  const profilePayload = {
    id: clientId,
    email: email.trim(),
    role: 'client',
  }

  const { error: profileError } = await supabase
    .from('profiles')
    .insert(profilePayload)

  if (profileError) {
    console.error('[invite-client] profile insert:', profileError.message)
    return NextResponse.json({ error: profileError.message }, { status: 500 })
  }

  const { error: linkError } = await supabase
    .from('coach_clients')
    .insert({ coach_id: coachId, client_id: clientId, status: 'new' })

  if (linkError) {
    console.error('[invite-client] link insert:', linkError.message)
    await supabase.from('profiles').delete().eq('id', clientId)
    return NextResponse.json({ error: linkError.message }, { status: 500 })
  }

  // Send the welcome email with the onboarding link
  let emailSent = false

  // Fetch the onboarding token generated by the migration default
  const { data: profile } = await supabase
    .from('profiles')
    .select('onboarding_token')
    .eq('id', clientId)
    .single()

  const { data: coachProfile } = await supabase
    .from('profiles')
    .select('full_name')
    .eq('id', coachId)
    .single()

  console.log('[invite-client] sendWelcomeEmail check — email:', email.trim(), 'onboarding_token found:', !!profile?.onboarding_token)

  if (profile?.onboarding_token) {
    console.log('[invite-client] calling sendWelcomeEmail...')
    const result = await sendWelcomeEmail({
      to: email.trim(),
      coachName: coachProfile?.full_name ?? 'Treneren din',
      onboardingToken: profile.onboarding_token,
    })
    console.log('[invite-client] sendWelcomeEmail result:', JSON.stringify(result))
    emailSent = result.ok
    if (result.ok) {
      await supabase
        .from('profiles')
        .update({ onboarding_email_sent_at: new Date().toISOString() })
        .eq('id', clientId)
    } else {
      console.error('[invite-client] email failed:', result.error)
    }
  } else {
    console.warn('[invite-client] skipping email — no onboarding_token on profile', clientId)
  }

  return NextResponse.json({ success: true, clientId, emailSent })
}
