import { createClient } from '@/lib/supabase/server'
import { NextResponse } from 'next/server'
import { sendWelcomeEmail } from '@/lib/email'

export async function POST(req: Request) {
  const { fullName, email, coachId } = await req.json()

  if (!fullName?.trim() || !coachId) {
    return NextResponse.json({ error: 'Mangler navn' }, { status: 400 })
  }

  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()

  if (!user || user.id !== coachId) {
    return NextResponse.json({ error: 'Ikke autorisert' }, { status: 401 })
  }

  const clientId = crypto.randomUUID()

  const profilePayload: Record<string, unknown> = {
    id: clientId,
    full_name: fullName.trim(),
    role: 'client',
  }
  if (email?.trim()) profilePayload.email = email.trim()

  const { error: profileError } = await supabase
    .from('profiles')
    .insert(profilePayload)

  if (profileError) {
    console.error('[invite-client] profile insert:', profileError.message)
    return NextResponse.json({ error: profileError.message }, { status: 500 })
  }

  const { error: linkError } = await supabase
    .from('coach_clients')
    .insert({ coach_id: coachId, client_id: clientId, status: 'new' })

  if (linkError) {
    console.error('[invite-client] link insert:', linkError.message)
    await supabase.from('profiles').delete().eq('id', clientId)
    return NextResponse.json({ error: linkError.message }, { status: 500 })
  }

  // If email provided, send the welcome email with the onboarding link
  let emailSent = false
  if (email?.trim()) {
    // Fetch the onboarding token generated by the migration default
    const { data: profile } = await supabase
      .from('profiles')
      .select('onboarding_token')
      .eq('id', clientId)
      .single()

    const { data: coachProfile } = await supabase
      .from('profiles')
      .select('full_name')
      .eq('id', coachId)
      .single()

    console.log('[invite-client] sendWelcomeEmail check — email:', email.trim(), 'onboarding_token found:', !!profile?.onboarding_token)

    if (profile?.onboarding_token) {
      console.log('[invite-client] calling sendWelcomeEmail...')
      const result = await sendWelcomeEmail({
        to: email.trim(),
        clientName: fullName.trim(),
        coachName: coachProfile?.full_name ?? 'Treneren din',
        onboardingToken: profile.onboarding_token,
      })
      console.log('[invite-client] sendWelcomeEmail result:', JSON.stringify(result))
      emailSent = result.ok
      if (!result.ok) {
        console.error('[invite-client] email failed:', result.error)
      }
    } else {
      console.warn('[invite-client] skipping email — no onboarding_token on profile', clientId)
    }
  }

  return NextResponse.json({ success: true, clientId, emailSent })
}
